### ISSUE TITLE
pip3 install http_parser compile error

### ISSUE THREAD

**Issue by SailM23** [benoitc/http-parser#80]
pip install --global-option build_ext http_parser
c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\pip\_internal\commands\install.py:211: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Collecting http_parser
  Using cached https://files.pythonhosted.org/packages/07/c4/22e3c76c2313c26dd5f84f1205b916ff38ea951aab0c4544b6e2f5920d64/http-parser-0.8.3.tar.gz
Installing collected packages: http-parser
  Running setup.py install for http-parser ... error
    Complete output from command c:\users\admin\appdata\local\programs\python\python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-u90otn1h\\http-parser\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" build_ext install --record C:\Users\Admin\AppData\Local\Temp\pip-record-9jb7firz\install-record.txt --single-version-externally-managed --compile:
    running build_ext
    building 'http_parser.parser' extension
    creating build
    creating build\temp.win32-3.7
    creating build\temp.win32-3.7\Release
    creating build\temp.win32-3.7\Release\http_parser
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iparser -Ic:\users\admin\appdata\local\programs\python\python37-32\include -Ic:\users\admin\appdata\local\programs\python\python37-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tchttp_parser\http_parser.c /Fobuild\temp.win32-3.7\Release\http_parser\http_parser.obj
    http_parser.c
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iparser -Ic:\users\admin\appdata\local\programs\python\python37-32\include -Ic:\users\admin\appdata\local\programs\python\python37-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tchttp_parser\parser.c /Fobuild\temp.win32-3.7\Release\http_parser\parser.obj
    parser.c
    http_parser\parser.c(6249): error C2039: 'exc_type': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(6250): error C2039: 'exc_value': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(6251): error C2039: 'exc_traceback': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(6252): error C2039: 'exc_type': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(6253): error C2039: 'exc_value': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(6254): error C2039: 'exc_traceback': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7460): error C2039: 'exc_type': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7461): error C2039: 'exc_value': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7462): error C2039: 'exc_traceback': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7474): error C2039: 'exc_type': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7475): error C2039: 'exc_value': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7476): error C2039: 'exc_traceback': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7477): error C2039: 'exc_type': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7478): error C2039: 'exc_value': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7479): error C2039: 'exc_traceback': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\users\admin\appdata\local\programs\python\python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-u90otn1h\\http-parser\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" build_ext install --record C:\Users\Admin\AppData\Local\Temp\pip-record-9jb7firz\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Admin\AppData\Local\Temp\pip-install-u90otn1h\http-parser\

C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\Scripts>pip3 install http_parser

**Comment by vsobotka** [comment]
Have you solved it? I get it too.

**Comment by SailM23** [comment]
Switching to python 3.4+ version resolved the issue.

**Comment by benoitc** [comment]
what was your python version 3.7 ? Did you test it outside of windows?

**Comment by SailM23** [comment]
3.6. windows and linux

**Comment by Strixx76** [comment]
I can confirm that it is not working in Python 3.7.3 on Windows 10.

I have been struggling with this for two days now. And tried every suggested solution on Stack Overflow. But the only thing that solves it is to down grade Python to 3.6.

Found several threads on Stack Overflow, and a lot of issues here on GitHub for other packages on PyPi. Could it be a Python issue and not a package issue?

```
running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\http_parser
    copying http_parser\http.py -> build\lib.win-amd64-3.7\http_parser
    copying http_parser\pyparser.py -> build\lib.win-amd64-3.7\http_parser
    copying http_parser\reader.py -> build\lib.win-amd64-3.7\http_parser
    copying http_parser\util.py -> build\lib.win-amd64-3.7\http_parser
    copying http_parser\_socketio.py -> build\lib.win-amd64-3.7\http_parser
    copying http_parser\__init__.py -> build\lib.win-amd64-3.7\http_parser
    running build_ext
    building 'http_parser.parser' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\http_parser
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.20.27508\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iparser "-Ic:\program files\python37\include" "-Ic:\program files\python37\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.20.27508\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /Tchttp_parser\http_parser.c /Fobuild\temp.win-amd64-3.7\Release\http_parser\http_parser.obj
    http_parser.c
    http_parser\http_parser.c(2024): warning C4244: '=': conversion from '__int64' to 'uint16_t', possible loss of data
    http_parser\http_parser.c(2031): warning C4244: '=': conversion from '__int64' to 'uint16_t', possible loss of data
    http_parser\http_parser.c(2038): warning C4244: '=': conversion from '__int64' to 'uint16_t', possible loss of data
    http_parser\http_parser.c(2047): warning C4244: '=': conversion from '__int64' to 'uint16_t', possible loss of data
    http_parser\http_parser.c(2140): warning C4244: '=': conversion from '__int64' to 'uint16_t', possible loss of data
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.20.27508\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iparser "-Ic:\program files\python37\include" "-Ic:\program files\python37\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.20.27508\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /Tchttp_parser\parser.c /Fobuild\temp.win-amd64-3.7\Release\http_parser\parser.obj
    parser.c
    http_parser\parser.c(6249): error C2039: 'exc_type': is not a member of '_ts'
    c:\program files\python37\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(6250): error C2039: 'exc_value': is not a member of '_ts'
    c:\program files\python37\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(6251): error C2039: 'exc_traceback': is not a member of '_ts'
    c:\program files\python37\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(6252): error C2039: 'exc_type': is not a member of '_ts'
    c:\program files\python37\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(6253): error C2039: 'exc_value': is not a member of '_ts'
    c:\program files\python37\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(6254): error C2039: 'exc_traceback': is not a member of '_ts'
    c:\program files\python37\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7460): error C2039: 'exc_type': is not a member of '_ts'
    c:\program files\python37\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7461): error C2039: 'exc_value': is not a member of '_ts'
    c:\program files\python37\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7462): error C2039: 'exc_traceback': is not a member of '_ts'
    c:\program files\python37\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7474): error C2039: 'exc_type': is not a member of '_ts'
    c:\program files\python37\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7475): error C2039: 'exc_value': is not a member of '_ts'
    c:\program files\python37\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7476): error C2039: 'exc_traceback': is not a member of '_ts'
    c:\program files\python37\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7477): error C2039: 'exc_type': is not a member of '_ts'
    c:\program files\python37\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7478): error C2039: 'exc_value': is not a member of '_ts'
    c:\program files\python37\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7479): error C2039: 'exc_traceback': is not a member of '_ts'
    c:\program files\python37\include\pystate.h(212): note: see declaration of '_ts'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.20.27508\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
```

**Comment by tatuylonen** [comment]
I'm getting this too.  Python 3.7.3 on Debian testing (default python3 version for this distribution).  This is blocking other important work.  Any hope for a fix soon?

**Comment by tatuylonen** [comment]
This appears to be fixed in github ("pip3 install git+https://github.com/benoitc/http-parser" works) but the latest release on pypi is from 2013.  Would it be possible to release an updated version on pypi sometime soon?  While one can install http-parser direct from github, there are other packages (e.g., pymesos) that depend on http-parser, and cannot now be installed in the normal way due to a dependency on http-parser.  In any case, thanks for the fix in github!

**Comment by di3663** [comment]
> This appears to be fixed in github ("pip3 install git+https://github.com/benoitc/http-parser" works on Linux) but the latest release on pypi is from 2013. Would it be possible to release an updated version on pypi sometime soon? While one can install http-parser direct from github, there are other packages (e.g., pymesos) that depend on http-parser, and cannot now be installed in the normal way due to a dependency on http-parser. In any case, thanks for the fix in github!

Thanks, works on msys2(windows python3.74.) too.

```
pacman -S mingw-w64-i686-cython
pip3 install git+https://github.com/benoitc/http-parser
pip3 install uvwsgi
```

**Comment by interfect** [comment]
I've been seeing similar errors about `exc_traceback` not being defined when trying to install the Github master on Mac. It seems like rerunning cython (`make clean` and `make`) sorts it out.

**Comment by adamnovak** [comment]
I'm still running into complaints about a missing `exc_type`/`exc_value`/`exc_traceback` members when building the current master branch on Mac against Python 3.7. Rerunning Cython (`make clean` and `make`) seems to solve it.

**Comment by adamnovak** [comment]
OK, the reason installing from Git only sometimes works is that if you install from Git it will run the Makefile (which gets renamed in the release process) and it will rebuild the C code using whatever Cython you have handy. If you don't have Cython installed, it will fail, and if your Cython is too old and generates code that mistakenly tries to use exc_whatever, it will not compile.

**Comment by ViCrack** [comment]
I got same issue

**Comment by benoitc** [comment]
fixed in 0.9

**Comment by maifeeulasad** [comment]
Just use : 
```
sudo apt-get install python-dev     #on python 2.x
sudo apt-get install python3-dev   #on python 3.x
```
Worked on Ubuntu 20.04LTS with python 2.x
