### PR TITLE
Rerun cython to fix complaints about exc_traceback

### LINKED ISSUE #80: pip3 install http_parser compile error
pip install --global-option build_ext http_parser
c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\pip\_internal\commands\install.py:211: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Collecting http_parser
  Using cached https://files.pythonhosted.org/packages/07/c4/22e3c76c2313c26dd5f84f1205b916ff38ea951aab0c4544b6e2f5920d64/http-parser-0.8.3.tar.gz
Installing collected packages: http-parser
  Running setup.py install for http-parser ... error
    Complete output from command c:\users\admin\appdata\local\programs\python\python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-u90otn1h\\http-parser\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" build_ext install --record C:\Users\Admin\AppData\Local\Temp\pip-record-9jb7firz\install-record.txt --single-version-externally-managed --compile:
    running build_ext
    building 'http_parser.parser' extension
    creating build
    creating build\temp.win32-3.7
    creating build\temp.win32-3.7\Release
    creating build\temp.win32-3.7\Release\http_parser
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iparser -Ic:\users\admin\appdata\local\programs\python\python37-32\include -Ic:\users\admin\appdata\local\programs\python\python37-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tchttp_parser\http_parser.c /Fobuild\temp.win32-3.7\Release\http_parser\http_parser.obj
    http_parser.c
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iparser -Ic:\users\admin\appdata\local\programs\python\python37-32\include -Ic:\users\admin\appdata\local\programs\python\python37-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tchttp_parser\parser.c /Fobuild\temp.win32-3.7\Release\http_parser\parser.obj
    parser.c
    http_parser\parser.c(6249): error C2039: 'exc_type': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(6250): error C2039: 'exc_value': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(6251): error C2039: 'exc_traceback': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(6252): error C2039: 'exc_type': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(6253): error C2039: 'exc_value': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(6254): error C2039: 'exc_traceback': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7460): error C2039: 'exc_type': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7461): error C2039: 'exc_value': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7462): error C2039: 'exc_traceback': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7474): error C2039: 'exc_type': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7475): error C2039: 'exc_value': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7476): error C2039: 'exc_traceback': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7477): error C2039: 'exc_type': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7478): error C2039: 'exc_value': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7479): error C2039: 'exc_traceback': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\users\admin\appdata\local\programs\python\python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-u90otn1h\\http-parser\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" build_ext install --record C:\Users\Admin\AppData\Local\Temp\pip-record-9jb7firz\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Admin\AppData\Local\Temp\pip-install-u90otn1h\http-parser\

C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\Scripts>pip3 install http_parser

### PR DESCRIPTION
**Pull request by adamnovak**
This should fix #80. It makes the C code with a newer cython, which protects access to the `exc_whatever` types which may or may not exist with a better macro.

I've tested this and it builds on 2.7 and 3.7 on Mac for me.

### CODE REVIEW

**Comment by adamnovak** [comment]
I think the real reason this worked for me is that as part of this I installed a modern version of cython. I used to be using an ancient Python 2.7 version, and it was getting run for builds from Git due to the Makefile still being in place. I don't think this will actually do anything for #80 after all.
